---
# This will be the initial Ansible Configuration for our Goland Web

- name: Initial configuration
  hosts: localhost
  vars:
    - version: 1.22.2

  tasks:
    - name: Initiating the Ansible process
      ansible.builtin.debug:
        msg:
        - "Initiating the Ansible tasks"

    - name: Download goland
      command: wget https://go.dev/dl/go{{version}}.linux-amd64.tar.gz

    - name: Delete previous installation
      command: rm -rf /usr/local/go
      become: true

    - name: Extract and move new go folder to /usr/local
      command: tar -C /usr/local -xzf go{{version}}.linux-amd64.tar.gz
      become: true

    - name: Delete downloaded tar file
      shell: rm -rf go{{version}}.linux-amd64.tar.gz*

    - name: Add go binary PATH to ~/.profile
      lineinfile:
        path: ~/.profile
        line: 'export PATH=$PATH:/usr/local/go/bin:$GOPATH/bin'
        create: true
        state: present

    - name: Add go binary PATH to ~/.bashrc
      lineinfile:
        path: ~/.bashrc
        line: 'export PATH=$PATH:/usr/local/go/bin:$GOPATH/bin'
        create: true
        state: present

    - name: Source updated profile and test GO version
      shell: . ~/.profile && go version
      register: goversion

    - name: View the Go version
      ansible.builtin.debug:
        msg:
        - "The Goland Version is {{ goversion.stdout }}"


